language: python
python:
  - 3.9.5
jobs:
  include:
    - stage: test
      name: pytest
      install:
        - pip install --upgrade pytest
        - pip install -e .
      script: pytest
    - stage: test
      name: pre-commit
      install: pip install pre-commit
      script: pre-commit run --all-files
deploy:
  provider: pypi
  username: __token__
  skip_existing: true
  password:
    secure: UA30xh0MAb+9TgPPlOveybmQ8HbjIN7piXk7tOHsR0Qf03EJfDYFItAEDHJdoqXm+NpwY4zmrfUHjlEd3qEEz+5QQ6Dv8WVrKh1r/H/7bv0WEW9A2DA/Mw9LC4cBK3NJb0HvDXRmEe2MU7iu2K/wP+1ySHl3yA0Gm3/1KMuuU8NCIWneKr+87j1A9yASRIHjN6Ke1yxbj5Y+iykqTLFbtvSxt5Ut82BrtCbxYqCVfdboTBfBleR5caXmKCVR23YZEgR8/uTY/ppWBm1bC7Dn4iLhpKmOeX06WxrdWM1XJZYcqa+jnkR8KA0h5ddKjWNP/BqJZspWVWqFw9U5Rmm4jFa897VDV/u6AWcdXvgkC+k6gr2GsjiLH00TvzL+EbhLDZZViSlcVjqoyphytgW1Vu/iS3kZxAwmin29Hr4PwnyyHzRGoFfCYhX0V655vTsjn9INcGmI3sdFFreFc3aCodMW9TQeiLU/awWQgvVdXOPkS/FxHtRMkBimHjAa8OKHkSu+8sjCDJEN0MaoOab1CLTpbir5ifK0FUepX76Z0lZNauM4ydeSawAaejygJFgq1refZTLMrB07r1EZgqD5rAUpaMapuWkWLUd2C0CZWXq+jo5dfiSaU3PrkEtPR6TJjk2rXphXMMMtV8jiZN92mI8Pm3Qrc4XBL++mk68zzE8=
